export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const FETCH_DETAILS_LOADING = "FETCH_DETAILS_LOADING";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";

export const UPDATE_DETAILS_LOADING = "UPDATE_DETAILS_LOADING";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
